"""
CEval Demo — Adult Income Dataset
==================================
This example shows how to use CEval to evaluate counterfactual explanations
generated by the DiCE explainer on the classic Adult Income dataset.

The goal of the Adult Income classification task is to predict whether a
person earns more than $50K/year.  We generate counterfactuals that show
users what minimal changes would flip the prediction to ">50K".

Paper:  Bayrak, B., & Bach, K. (2024).  Evaluation of Instance-Based
        Explanations: An In-Depth Analysis of Counterfactual Evaluation Metrics,
        Challenges, and the CEval Toolkit.  IEEE Access.
        https://ieeexplore.ieee.org/document/10550910
PyPI:   https://pypi.org/project/CEval/
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import dice_ml
from dice_ml import Dice

# ── 1. Load dataset ───────────────────────────────────────────────────────────
print("=" * 60)
print("  CEval Demo  |  Adult Income Dataset")
print("=" * 60)

label = "income"
feature_cols = ["age", "education_num", "hours_per_week",
                "capital_gain", "capital_loss"]

url = ("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data")

col_names = [
    "age", "workclass", "fnlwgt", "education", "education_num",
    "marital_status", "occupation", "relationship", "race", "sex",
    "capital_gain", "capital_loss", "hours_per_week", "native_country",
    label,
]

try:
    df_raw = pd.read_csv(url, names=col_names, sep=",\\s*", engine="python", na_values="?")
    df_raw = df_raw.dropna()
    df_raw[label] = df_raw[label].str.strip().map({"<=50K": 0, ">50K": 1}).fillna(0).astype(int)
    df = df_raw[feature_cols + [label]].sample(n=2000, random_state=42).reset_index(drop=True)
    print("[INFO] Loaded UCI Adult Income dataset.")
except Exception:
    # Fully offline fallback with realistic synthetic data
    rng = np.random.default_rng(42)
    n = 1000
    age          = rng.integers(18, 70, n)
    education_num = rng.integers(1, 16, n)
    hours_per_week = rng.integers(20, 60, n)
    capital_gain = (rng.random(n) > 0.85).astype(int) * rng.integers(1000, 10000, n)
    capital_loss = (rng.random(n) > 0.92).astype(int) * rng.integers(100, 2000, n)
    # Simple proxy label: higher education + more hours → more likely >50K
    score = 0.05 * education_num + 0.01 * hours_per_week + 0.0001 * capital_gain
    income = (score > rng.uniform(0.4, 1.2, n)).astype(int)
    df = pd.DataFrame({
        "age": age, "education_num": education_num,
        "hours_per_week": hours_per_week,
        "capital_gain": capital_gain, "capital_loss": capital_loss,
        label: income,
    })
    print("[INFO] Using synthetic data (offline mode).")

print(f"\nDataset loaded: {len(df)} rows, {len(feature_cols)} features")
print(f"Label distribution:\n{df[label].value_counts().to_string()}\n")

# ── 3. Train / test split ──────────────────────────────────────────────────────
X = df[feature_cols]
y = df[label]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42, stratify=y
)

train_df = X_train.copy(); train_df[label] = y_train.values
test_df  = X_test.copy();  test_df[label]  = y_test.values

# Sample a few instances to explain (keep runtime short)
N_EXPLAIN = 10
test_sample = test_df.sample(n=N_EXPLAIN, random_state=7).reset_index(drop=True)

# ── 4. Train classifier ────────────────────────────────────────────────────────
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)
acc = clf.score(X_test, y_test)
print(f"RandomForest accuracy on test set: {acc:.2%}\n")

# ── 5. Generate counterfactuals with DiCE ──────────────────────────────────────
print("Generating counterfactuals with DiCE …")

dice_data  = dice_ml.Data(dataframe=train_df, continuous_features=feature_cols,
                          outcome_name=label)
dice_model = dice_ml.Model(model=clf, backend="sklearn", model_type="classifier")
explainer  = Dice(dice_data, dice_model, method="random")

# 1-to-1  (one CF per instance)
print("  → 1-to-1 mode (1 CF per instance)")
cfs_1to1 = []
for i in range(N_EXPLAIN):
    row = test_sample.drop(columns=[label]).iloc[i:i+1]
    res = explainer.generate_counterfactuals(row, total_CFs=1,
                                              desired_class="opposite",
                                              verbose=False)
    cf_df = res.cf_examples_list[0].final_cfs_df
    if cf_df is not None and len(cf_df) > 0:
        cfs_1to1.append(cf_df.iloc[0])
    else:
        # Fallback: copy the original with label flipped
        fallback = test_sample.iloc[i].copy()
        fallback[label] = 1 - fallback[label]
        cfs_1to1.append(fallback)

cfs_1to1_df = pd.DataFrame(cfs_1to1).reset_index(drop=True)
cfs_1to1_df[label] = cfs_1to1_df[label].astype(int)
print(f"     Generated {len(cfs_1to1_df)} counterfactuals\n")

# 1-to-N  (three CFs per instance)
print("  → 1-to-N mode (3 CFs per instance)")
cfs_1toN_rows = []
for i in range(N_EXPLAIN):
    row = test_sample.drop(columns=[label]).iloc[i:i+1]
    res = explainer.generate_counterfactuals(row, total_CFs=3,
                                              desired_class="opposite",
                                              verbose=False)
    cf_df = res.cf_examples_list[0].final_cfs_df
    if cf_df is not None and len(cf_df) > 0:
        for _, r in cf_df.iterrows():
            r = r.copy(); r["instance"] = i
            cfs_1toN_rows.append(r)
    else:
        for _ in range(3):
            fallback = test_sample.iloc[i].copy()
            fallback[label] = 1 - fallback[label]
            fallback["instance"] = i
            cfs_1toN_rows.append(fallback)

cfs_1toN_df = pd.DataFrame(cfs_1toN_rows).reset_index(drop=True)
cfs_1toN_df[label] = cfs_1toN_df[label].astype(int)
print(f"     Generated {len(cfs_1toN_df)} counterfactuals (total)\n")

# ── 6. Evaluate with CEval ─────────────────────────────────────────────────────
print("Evaluating with CEval …\n")

# Add ceval directory to path so we can import the local dev version
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from ceval import CEval

# Constraints: age should not change (immutable feature)
immutable = ["age"] if "age" in feature_cols else []

evaluator = CEval(
    samples=test_sample,
    label=label,
    data=train_df,
    model=clf,
    k_nn=5,
    constraints=immutable,
)

# Register 1-to-1 explanations
evaluator.add_explainer(
    name="DiCE (1-to-1)",
    explanations=cfs_1to1_df,
    exp_type="generated-cf",
    mode="1to1",
)

# Register 1-to-N explanations
evaluator.add_explainer(
    name="DiCE (1-to-N)",
    explanations=cfs_1toN_df,
    exp_type="generated-cf",
    mode="1toN",
)

# ── 7. Results ─────────────────────────────────────────────────────────────────
print("=" * 60)
print("  Evaluation Results")
print("=" * 60)
result_T = evaluator.comparison_table.T
print(result_T.to_string())
print()

# Summary
print("=" * 60)
print("  Key Metrics (DiCE 1-to-1)")
print("=" * 60)
row = evaluator.comparison_table.loc["DiCE (1-to-1)"]
key_metrics = ["validity", "proximity", "sparsity", "feasibility",
               "redundancy", "constraint_violation"]
for m in key_metrics:
    v = row.get(m, "-")
    if v != "-":
        print(f"  {m:<25} {v}")
